# profile dev properties
app:
  db-name: resourcesystem
  db-host: localhost
  db-port: 5432
  db-username: postgres
  db-password: postgres

spring:
  datasource:
    username: ${app.db-username}
    password: ${app.db-password}
